
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class Aoe : Luban.BeanBase
{
    public Aoe(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        Name = (string)_obj.GetValue("Name");
        Prefab = (string)_obj.GetValue("Prefab");
        { var __json0 = _obj.GetValue("Tags"); int _n0 = (__json0 as JArray).Count; Tags = new string[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Tags[__index0++] = __v0; }   }
        TickTime = (float)_obj.GetValue("TickTime");
    }

    public static Aoe DeserializeAoe(JToken _buf)
    {
        return new Aoe(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 预制体
    /// </summary>
    public readonly string Prefab;
    public readonly string[] Tags;
    /// <summary>
    /// 工作周期，单位秒
    /// </summary>
    public readonly float TickTime;


    public const int __ID__ = 66007;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Prefab:" + Prefab + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "TickTime:" + TickTime + ","
        + "}";
    }
}
}

