
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class Buff : Luban.BeanBase
{
    public Buff(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (string)_obj.GetValue("Id");
        Name = (string)_obj.GetValue("Name");
        Priority = (int)_obj.GetValue("Priority");
        MaxStack = (int)_obj.GetValue("MaxStack");
        TickTime = (float)_obj.GetValue("TickTime");
        { var __json0 = _obj.GetValue("Event"); Event = new System.Collections.Generic.Dictionary<string, string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string _k0;  _k0 = (string)__e0[0]; string _v0;  _v0 = (string)__e0[1];  Event.Add(_k0, _v0); }   }
    }

    public static Buff DeserializeBuff(JToken _buf)
    {
        return new Buff(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 可堆叠最大层数
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 工作周期，单位秒
    /// </summary>
    public readonly float TickTime;
    /// <summary>
    /// 时机方法
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, string> Event;


    public const int __ID__ = 2081907;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Priority:" + Priority + ","
        + "MaxStack:" + MaxStack + ","
        + "TickTime:" + TickTime + ","
        + "Event:" + Luban.StringUtil.CollectionToString(Event) + ","
        + "}";
    }
}
}

