
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public partial struct CastCondition
{
    public CastCondition(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        HP = (int)_obj.GetValue("HP");
        Shield = (int)_obj.GetValue("Shield");
    }

    public static CastCondition DeserializeCastCondition(JToken _buf)
    {
        return new CastCondition(_buf);
    }

    /// <summary>
    /// 生命值
    /// </summary>
    public readonly int HP;
    /// <summary>
    /// 护盾值
    /// </summary>
    public readonly int Shield;



    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "HP:" + HP + ","
        + "Shield:" + Shield + ","
        + "}";
    }
}
}

