
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public partial struct CastRule
{
    public CastRule(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Cast = (int)_obj.GetValue("Cast");
        CD = (int)_obj.GetValue("CD");
    }

    public static CastRule DeserializeCastRule(JToken _buf)
    {
        return new CastRule(_buf);
    }

    /// <summary>
    /// 释放回合
    /// </summary>
    public readonly int Cast;
    /// <summary>
    /// 冷却回合
    /// </summary>
    public readonly int CD;



    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Cast:" + Cast + ","
        + "CD:" + CD + ","
        + "}";
    }
}
}

