
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class CreateDamageWarp : Luban.BeanBase
{
    public CreateDamageWarp(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        DamageType = (EDamageType)(int)_obj.GetValue("DamageType");
        DamageAttr = (EDamageAttr)(int)_obj.GetValue("DamageAttr");
        Ratio = (float)_obj.GetValue("Ratio");
        FixedValue = (int)_obj.GetValue("FixedValue");
        BeHurtEffect = (string)_obj.GetValue("BeHurtEffect");
    }

    public static CreateDamageWarp DeserializeCreateDamageWarp(JToken _buf)
    {
        return new CreateDamageWarp(_buf);
    }

    /// <summary>
    /// 伤害类型
    /// </summary>
    public readonly EDamageType DamageType;
    /// <summary>
    /// 伤害属性
    /// </summary>
    public readonly EDamageAttr DamageAttr;
    /// <summary>
    /// 伤害比例
    /// </summary>
    public readonly float Ratio;
    /// <summary>
    /// 伤害固定值
    /// </summary>
    public readonly int FixedValue;
    /// <summary>
    /// 被打的特效
    /// </summary>
    public readonly string BeHurtEffect;


    public const int __ID__ = -792069933;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DamageType:" + DamageType + ","
        + "DamageAttr:" + DamageAttr + ","
        + "Ratio:" + Ratio + ","
        + "FixedValue:" + FixedValue + ","
        + "BeHurtEffect:" + BeHurtEffect + ","
        + "}";
    }
}
}

