
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum EControlModType
    {
        /// <summary>
        /// 攻击状态
        /// </summary>
        CanAttack = 0,
        /// <summary>
        /// 技能状态
        /// </summary>
        CanSkill = 1,
        /// <summary>
        /// 死亡状态
        /// </summary>
        CanDead = 2,
        /// <summary>
        /// 受伤状态
        /// </summary>
        CanBeHurt = 3,
        /// <summary>
        /// 回复状态
        /// </summary>
        CanHeal = 4,
    }

} 

