
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum EDamageType
    {
        /// <summary>
        /// 物理输出
        /// </summary>
        PhysicsDamage = 0,
        /// <summary>
        /// 魔法输出
        /// </summary>
        MagicDamage = 1,
        /// <summary>
        /// 生命回复
        /// </summary>
        Health = 2,
    }

} 

