
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum EDamageType
    {
        /// <summary>
        /// 固定值
        /// </summary>
        Fixed = 0,
        /// <summary>
        /// 乘法
        /// </summary>
        Mult = 1,
    }

} 

