
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum EEquipmetType
    {
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 0,
        /// <summary>
        /// 手套
        /// </summary>
        Glove = 1,
        /// <summary>
        /// 战甲
        /// </summary>
        Armour = 2,
        /// <summary>
        /// 战靴
        /// </summary>
        Shoes = 3,
    }

} 

