
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class EffectTime : Luban.BeanBase
{
    public EffectTime(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Key = (string)_obj.GetValue("Key");
    }

    public static EffectTime DeserializeEffectTime(JToken _buf)
    {
        return new EffectTime(_buf);
    }

    /// <summary>
    /// Key
    /// </summary>
    public readonly string Key;


    public const int __ID__ = -585683938;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "}";
    }
}
}

