
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum EProfession
    {
        /// <summary>
        /// 物理输出
        /// </summary>
        Physics = 0,
        /// <summary>
        /// 魔法输出
        /// </summary>
        Magic = 1,
        /// <summary>
        /// 前排肉盾
        /// </summary>
        Tank = 2,
        /// <summary>
        /// 辅助
        /// </summary>
        Auxiliary = 3,
    }

} 

