
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum EProfession
    {
        /// <summary>
        /// 战士
        /// </summary>
        Warrior = 0,
        /// <summary>
        /// 刺客
        /// </summary>
        Assassin = 1,
        /// <summary>
        /// 坦克
        /// </summary>
        Tank = 2,
        /// <summary>
        /// 辅助
        /// </summary>
        Auxiliary = 3,
    }

} 

