
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum EPropertyModType
    {
        /// <summary>
        /// 生命值
        /// </summary>
        HP = 0,
        /// <summary>
        /// 生命值比例
        /// </summary>
        HPRatio = 1,
        /// <summary>
        /// 攻击力
        /// </summary>
        Attack = 2,
        /// <summary>
        /// 攻击力比例
        /// </summary>
        AttackRatio = 3,
        /// <summary>
        /// 物理防御力
        /// </summary>
        PhysicalDefense = 4,
        /// <summary>
        /// 物理防御力比例
        /// </summary>
        PhysicalDefenseRatio = 5,
        /// <summary>
        /// 魔法防御力
        /// </summary>
        MagicDefense = 6,
        /// <summary>
        /// 魔法防御力比例
        /// </summary>
        MagicDefenseRatio = 7,
        /// <summary>
        /// 暴击率比例
        /// </summary>
        CriticalRate = 8,
        /// <summary>
        /// 护盾值
        /// </summary>
        Shiled = 9,
    }

} 

