
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum EQuality
    {
        /// <summary>
        /// 小将
        /// </summary>
        White = 0,
        /// <summary>
        /// 良将
        /// </summary>
        Blue = 1,
        /// <summary>
        /// 名将
        /// </summary>
        Purple = 2,
        /// <summary>
        /// 神将
        /// </summary>
        Orange = 3,
        /// <summary>
        /// 超神将
        /// </summary>
        Red = 4,
    }

} 

