
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum ERemoveBuffType
    {
        /// <summary>
        /// 随机Buff
        /// </summary>
        RandomBuff = 0,
        /// <summary>
        /// 随机Debuff
        /// </summary>
        RandomDebuff = 1,
        /// <summary>
        /// 指定Buff
        /// </summary>
        AssignBuff = 2,
    }

} 

