
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum ETargetFliter
    {
        /// <summary>
        /// 英雄数量最多的一排
        /// </summary>
        LargestRow = 0,
        /// <summary>
        /// 攻击力最高的英雄
        /// </summary>
        HighestAttack = 1,
        /// <summary>
        /// 前排英雄
        /// </summary>
        FrontRow = 2,
        /// <summary>
        /// 后排英雄
        /// </summary>
        RearRow = 3,
        /// <summary>
        /// 随机英雄
        /// </summary>
        Random = 4,
        /// <summary>
        /// 生命力最低的英雄
        /// </summary>
        LowestHealth = 5,
    }

} 

