
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MyGame
{ 
    public enum ETargetCamp
    {
        /// <summary>
        /// 我方
        /// </summary>
        My = 0,
        /// <summary>
        /// 敌方
        /// </summary>
        Other = 1,
    }

} 

