
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public partial struct EventWarp
{
    public EventWarp(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Event = (string)_obj.GetValue("Event");
        { var __json0 = _obj.GetValue("Params"); Params = new System.Collections.Generic.List<mObject>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { mObject __v0;  __v0 = mObject.DeserializemObject(__e0);  Params.Add(__v0); }   }
    }

    public static EventWarp DeserializeEventWarp(JToken _buf)
    {
        return new EventWarp(_buf);
    }

    /// <summary>
    /// 方法名
    /// </summary>
    public readonly string Event;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly System.Collections.Generic.List<mObject> Params;



    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Params) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Event:" + Event + ","
        + "Params:" + Luban.StringUtil.CollectionToString(Params) + ","
        + "}";
    }
}
}

