
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class Hero : Luban.BeanBase
{
    public Hero(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        Name = (string)_obj.GetValue("Name");
        Prefab = (string)_obj.GetValue("Prefab");
        Quality = (EQuality)(int)_obj.GetValue("Quality");
        Profession = (EProfession)(int)_obj.GetValue("Profession");
        Hp = (int)_obj.GetValue("Hp");
        Attack = (int)_obj.GetValue("Attack");
        PhysicalDefense = (int)_obj.GetValue("PhysicalDefense");
        MagicDefense = (int)_obj.GetValue("MagicDefense");
        HpDelta = (int)_obj.GetValue("HpDelta");
        AttackDelta = (int)_obj.GetValue("AttackDelta");
        PhysicalDefenseDelta = (int)_obj.GetValue("PhysicalDefenseDelta");
        MagicDefenseDelta = (int)_obj.GetValue("MagicDefenseDelta");
        { var __json0 = _obj.GetValue("SkillGroupIds"); int _n0 = (__json0 as JArray).Count; SkillGroupIds = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  SkillGroupIds[__index0++] = __v0; }   }
        { var __json0 = _obj.GetValue("PassiveSkillGroupIds"); int _n0 = (__json0 as JArray).Count; PassiveSkillGroupIds = new int[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  PassiveSkillGroupIds[__index0++] = __v0; }   }
    }

    public static Hero DeserializeHero(JToken _buf)
    {
        return new Hero(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 品级
    /// </summary>
    public readonly EQuality Quality;
    /// <summary>
    /// 职业
    /// </summary>
    public readonly EProfession Profession;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 物理防御值
    /// </summary>
    public readonly int PhysicalDefense;
    /// <summary>
    /// 魔法防御值
    /// </summary>
    public readonly int MagicDefense;
    /// <summary>
    /// 生命值升级增量
    /// </summary>
    public readonly int HpDelta;
    /// <summary>
    /// 攻击力升级增量
    /// </summary>
    public readonly int AttackDelta;
    /// <summary>
    /// 物理防御升级增量
    /// </summary>
    public readonly int PhysicalDefenseDelta;
    /// <summary>
    /// 魔法防御升级增量
    /// </summary>
    public readonly int MagicDefenseDelta;
    /// <summary>
    /// 拥有的技能，1是普攻
    /// </summary>
    public readonly int[] SkillGroupIds;
    /// <summary>
    /// 拥有的被动技能
    /// </summary>
    public readonly int[] PassiveSkillGroupIds;


    public const int __ID__ = 2245658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Prefab:" + Prefab + ","
        + "Quality:" + Quality + ","
        + "Profession:" + Profession + ","
        + "Hp:" + Hp + ","
        + "Attack:" + Attack + ","
        + "PhysicalDefense:" + PhysicalDefense + ","
        + "MagicDefense:" + MagicDefense + ","
        + "HpDelta:" + HpDelta + ","
        + "AttackDelta:" + AttackDelta + ","
        + "PhysicalDefenseDelta:" + PhysicalDefenseDelta + ","
        + "MagicDefenseDelta:" + MagicDefenseDelta + ","
        + "SkillGroupIds:" + Luban.StringUtil.CollectionToString(SkillGroupIds) + ","
        + "PassiveSkillGroupIds:" + Luban.StringUtil.CollectionToString(PassiveSkillGroupIds) + ","
        + "}";
    }
}
}

