
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class mAddBuffWarp : mObject
{
    public mAddBuffWarp(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        Data = AddBuffWarp.DeserializeAddBuffWarp(_obj.GetValue("data"));
    }

    public static mAddBuffWarp DeserializemAddBuffWarp(JToken _buf)
    {
        return new mAddBuffWarp(_buf);
    }

    public readonly AddBuffWarp Data;


    public const int __ID__ = 356233871;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "data:" + Data + ","
        + "}";
    }
}
}

