
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class mBool : mObject
{
    public mBool(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        Data = (bool)_obj.GetValue("data");
    }

    public static mBool DeserializemBool(JToken _buf)
    {
        return new mBool(_buf);
    }

    public readonly bool Data;


    public const int __ID__ = 102740215;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "data:" + Data + ","
        + "}";
    }
}
}

