
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class mFloat : mObject
{
    public mFloat(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        Data = (float)_obj.GetValue("data");
    }

    public static mFloat DeserializemFloat(JToken _buf)
    {
        return new mFloat(_buf);
    }

    public readonly float Data;


    public const int __ID__ = -1106416145;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "data:" + Data + ","
        + "}";
    }
}
}

