
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class mPlayEffectWarp : mObject
{
    public mPlayEffectWarp(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        Data = PlayEffectWarp.DeserializePlayEffectWarp(_obj.GetValue("data"));
    }

    public static mPlayEffectWarp DeserializemPlayEffectWarp(JToken _buf)
    {
        return new mPlayEffectWarp(_buf);
    }

    public readonly PlayEffectWarp Data;


    public const int __ID__ = -1635610662;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Data?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "data:" + Data + ","
        + "}";
    }
}
}

