
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class mTargetWarp : mObject
{
    public mTargetWarp(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        Data = TargetWarp.DeserializeTargetWarp(_obj.GetValue("data"));
    }

    public static mTargetWarp DeserializemTargetWarp(JToken _buf)
    {
        return new mTargetWarp(_buf);
    }

    public readonly TargetWarp Data;


    public const int __ID__ = -114016250;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Data?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "data:" + Data + ","
        + "}";
    }
}
}

