
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class mTransferBuffWarp : mObject
{
    public mTransferBuffWarp(JToken _buf)  : base(_buf) 
    {
        JObject _obj = _buf as JObject;
        Data = TransferBuffWarp.DeserializeTransferBuffWarp(_obj.GetValue("data"));
    }

    public static mTransferBuffWarp DeserializemTransferBuffWarp(JToken _buf)
    {
        return new mTransferBuffWarp(_buf);
    }

    public readonly TransferBuffWarp Data;


    public const int __ID__ = 1236713747;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Data?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "data:" + Data + ","
        + "}";
    }
}
}

