
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public partial struct PropertyMod
{
    public PropertyMod(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        HP = (int)_obj.GetValue("HP");
        Attack = (int)_obj.GetValue("Attack");
        PhysicalDefense = (int)_obj.GetValue("PhysicalDefense");
        MagicDefense = (int)_obj.GetValue("MagicDefense");
    }

    public static PropertyMod DeserializePropertyMod(JToken _buf)
    {
        return new PropertyMod(_buf);
    }

    /// <summary>
    /// 生命值
    /// </summary>
    public readonly int HP;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 物理防御力
    /// </summary>
    public readonly int PhysicalDefense;
    /// <summary>
    /// 魔法防御力
    /// </summary>
    public readonly int MagicDefense;



    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "HP:" + HP + ","
        + "Attack:" + Attack + ","
        + "PhysicalDefense:" + PhysicalDefense + ","
        + "MagicDefense:" + MagicDefense + ","
        + "}";
    }
}
}

