
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class RemoveBuffWarp : Luban.BeanBase
{
    public RemoveBuffWarp(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        RemoveBuffType = (ERemoveBuffType)(int)_obj.GetValue("RemoveBuffType");
        BuffKey = (string)_obj.GetValue("BuffKey");
        Probability = (float)_obj.GetValue("Probability");
        Count = (int)_obj.GetValue("Count");
    }

    public static RemoveBuffWarp DeserializeRemoveBuffWarp(JToken _buf)
    {
        return new RemoveBuffWarp(_buf);
    }

    public readonly ERemoveBuffType RemoveBuffType;
    public readonly string BuffKey;
    public readonly float Probability;
    /// <summary>
    /// 0表示全部
    /// </summary>
    public readonly int Count;


    public const int __ID__ = 176052799;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RemoveBuffType:" + RemoveBuffType + ","
        + "BuffKey:" + BuffKey + ","
        + "Probability:" + Probability + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

