
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class Skill : Luban.BeanBase
{
    public Skill(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        Group = (int)_obj.GetValue("Group");
        Rule = CastRule.DeserializeCastRule(_obj.GetValue("Rule"));
        Condition = CastCondition.DeserializeCastCondition(_obj.GetValue("Condition"));
        Cost = CostResource.DeserializeCostResource(_obj.GetValue("Cost"));
        EffectKey = (string)_obj.GetValue("EffectKey");
        { var __json0 = _obj.GetValue("EffectValue"); int _n0 = (__json0 as JArray).Count; EffectValue = new EventWarp[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { EventWarp __v0;  __v0 = EventWarp.DeserializeEventWarp(__e0);  EffectValue[__index0++] = __v0; }   }
    }

    public static Skill DeserializeSkill(JToken _buf)
    {
        return new Skill(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能组
    /// </summary>
    public readonly int Group;
    /// <summary>
    /// 释放回合，冷却回合
    /// </summary>
    public readonly CastRule Rule;
    /// <summary>
    /// 技能释放条件
    /// </summary>
    public readonly CastCondition Condition;
    /// <summary>
    /// 技能消耗
    /// </summary>
    public readonly CostResource Cost;
    /// <summary>
    /// 时间轴Key
    /// </summary>
    public readonly string EffectKey;
    /// <summary>
    /// 时间轴里的方法参数
    /// </summary>
    public readonly EventWarp[] EffectValue;


    public const int __ID__ = 79944241;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Group:" + Group + ","
        + "Rule:" + Rule + ","
        + "Condition:" + Condition + ","
        + "Cost:" + Cost + ","
        + "EffectKey:" + EffectKey + ","
        + "EffectValue:" + Luban.StringUtil.CollectionToString(EffectValue) + ","
        + "}";
    }
}
}

