
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace MyGame
{
public partial class Tables
{
    public TbHero TbHero {get; }
    public TbSkill TbSkill {get; }
    public TbEffectTime TbEffectTime {get; }
    public TbAoe TbAoe {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbHero = new TbHero(loader("tbhero"));
        TbSkill = new TbSkill(loader("tbskill"));
        TbEffectTime = new TbEffectTime(loader("tbeffecttime"));
        TbAoe = new TbAoe(loader("tbaoe"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbHero.ResolveRef(this);
        TbSkill.ResolveRef(this);
        TbEffectTime.ResolveRef(this);
        TbAoe.ResolveRef(this);
    }
}

}

