
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace MyGame
{
public partial class Tables
{
    public TbHero TbHero {get; }
    public TbSkill TbSkill {get; }
    public TbTimeline TbTimeline {get; }
    public TbBuff TbBuff {get; }
    public TbPassiveSkill TbPassiveSkill {get; }
    public TbAddBuffDefine TbAddBuffDefine {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbHero = new TbHero(loader("tbhero"));
        TbSkill = new TbSkill(loader("tbskill"));
        TbTimeline = new TbTimeline(loader("tbtimeline"));
        TbBuff = new TbBuff(loader("tbbuff"));
        TbPassiveSkill = new TbPassiveSkill(loader("tbpassiveskill"));
        TbAddBuffDefine = new TbAddBuffDefine(loader("tbaddbuffdefine"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbHero.ResolveRef(this);
        TbSkill.ResolveRef(this);
        TbTimeline.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbPassiveSkill.ResolveRef(this);
        TbAddBuffDefine.ResolveRef(this);
    }
}

}

