
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class TargetWarp : Luban.BeanBase
{
    public TargetWarp(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        TargetCamp = (ETargetCamp)(int)_obj.GetValue("TargetCamp");
        TargetFliter = (ETargetFliter)(int)_obj.GetValue("TargetFliter");
        Count = (int)_obj.GetValue("Count");
    }

    public static TargetWarp DeserializeTargetWarp(JToken _buf)
    {
        return new TargetWarp(_buf);
    }

    /// <summary>
    /// 目标阵营
    /// </summary>
    public readonly ETargetCamp TargetCamp;
    /// <summary>
    /// 目标过滤
    /// </summary>
    public readonly ETargetFliter TargetFliter;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;


    public const int __ID__ = -1814813735;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TargetCamp:" + TargetCamp + ","
        + "TargetFliter:" + TargetFliter + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

