
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace MyGame
{

public partial class TbAddBuffDefine
{
    private readonly System.Collections.Generic.Dictionary<int, AddBuffDefine> _dataMap;
    private readonly System.Collections.Generic.List<AddBuffDefine> _dataList;
    
    public TbAddBuffDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AddBuffDefine>();
        _dataList = new System.Collections.Generic.List<AddBuffDefine>();
        
        foreach(JObject _ele in _buf)
        {
            AddBuffDefine _v;
            _v = AddBuffDefine.DeserializeAddBuffDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, AddBuffDefine> DataMap => _dataMap;
    public System.Collections.Generic.List<AddBuffDefine> DataList => _dataList;

    public AddBuffDefine GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AddBuffDefine Get(int key) => _dataMap[key];
    public AddBuffDefine this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

