
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace MyGame
{

public partial class TbAoe
{
    private readonly System.Collections.Generic.Dictionary<int, Aoe> _dataMap;
    private readonly System.Collections.Generic.List<Aoe> _dataList;
    
    public TbAoe(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Aoe>();
        _dataList = new System.Collections.Generic.List<Aoe>();
        
        foreach(JObject _ele in _buf)
        {
            Aoe _v;
            _v = Aoe.DeserializeAoe(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Aoe> DataMap => _dataMap;
    public System.Collections.Generic.List<Aoe> DataList => _dataList;

    public Aoe GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Aoe Get(int key) => _dataMap[key];
    public Aoe this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

