
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace MyGame
{

public partial class TbBuff
{
    private readonly System.Collections.Generic.Dictionary<string, Buff> _dataMap;
    private readonly System.Collections.Generic.List<Buff> _dataList;
    
    public TbBuff(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Buff>();
        _dataList = new System.Collections.Generic.List<Buff>();
        
        foreach(JObject _ele in _buf)
        {
            Buff _v;
            _v = Buff.DeserializeBuff(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<string, Buff> DataMap => _dataMap;
    public System.Collections.Generic.List<Buff> DataList => _dataList;

    public Buff GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Buff Get(string key) => _dataMap[key];
    public Buff this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

