
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace MyGame
{

public partial class TbEffectTime
{
    private readonly System.Collections.Generic.Dictionary<string, EffectTime> _dataMap;
    private readonly System.Collections.Generic.List<EffectTime> _dataList;
    
    public TbEffectTime(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, EffectTime>();
        _dataList = new System.Collections.Generic.List<EffectTime>();
        
        foreach(JObject _ele in _buf)
        {
            EffectTime _v;
            _v = EffectTime.DeserializeEffectTime(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
         }
    }


    public System.Collections.Generic.Dictionary<string, EffectTime> DataMap => _dataMap;
    public System.Collections.Generic.List<EffectTime> DataList => _dataList;

    public EffectTime GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EffectTime Get(string key) => _dataMap[key];
    public EffectTime this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

