
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace MyGame
{

public partial class TbPassiveSkill
{
    private readonly System.Collections.Generic.Dictionary<int, PassiveSkill> _dataMap;
    private readonly System.Collections.Generic.List<PassiveSkill> _dataList;
    
    public TbPassiveSkill(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PassiveSkill>();
        _dataList = new System.Collections.Generic.List<PassiveSkill>();
        
        foreach(JObject _ele in _buf)
        {
            PassiveSkill _v;
            _v = PassiveSkill.DeserializePassiveSkill(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, PassiveSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<PassiveSkill> DataList => _dataList;

    public PassiveSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PassiveSkill Get(int key) => _dataMap[key];
    public PassiveSkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

