
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace MyGame
{

public partial class TbTimeline
{
    private readonly System.Collections.Generic.Dictionary<string, Timeline> _dataMap;
    private readonly System.Collections.Generic.List<Timeline> _dataList;
    
    public TbTimeline(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Timeline>();
        _dataList = new System.Collections.Generic.List<Timeline>();
        
        foreach(JObject _ele in _buf)
        {
            Timeline _v;
            _v = Timeline.DeserializeTimeline(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
         }
    }


    public System.Collections.Generic.Dictionary<string, Timeline> DataMap => _dataMap;
    public System.Collections.Generic.List<Timeline> DataList => _dataList;

    public Timeline GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Timeline Get(string key) => _dataMap[key];
    public Timeline this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

