
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public partial struct TimelineNodeWarp
{
    public TimelineNodeWarp(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Elapsed = (float)_obj.GetValue("Elapsed");
        EventWarp = EventWarp.DeserializeEventWarp(_obj.GetValue("EventWarp"));
    }

    public static TimelineNodeWarp DeserializeTimelineNodeWarp(JToken _buf)
    {
        return new TimelineNodeWarp(_buf);
    }

    public readonly float Elapsed;
    public readonly EventWarp EventWarp;



    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Elapsed:" + Elapsed + ","
        + "EventWarp:" + EventWarp + ","
        + "}";
    }
}
}

