
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class Timeline : Luban.BeanBase
{
    public Timeline(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Key = (string)_obj.GetValue("Key");
        Duration = (float)_obj.GetValue("Duration");
        { var __json0 = _obj.GetValue("Node"); int _n0 = (__json0 as JArray).Count; Node = new TimelineNodeWarp[_n0]; int __index0=0; foreach(JToken __e0 in __json0) { TimelineNodeWarp __v0;  __v0 = TimelineNodeWarp.DeserializeTimelineNodeWarp(__e0);  Node[__index0++] = __v0; }   }
    }

    public static Timeline DeserializeTimeline(JToken _buf)
    {
        return new Timeline(_buf);
    }

    /// <summary>
    /// Key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 总时长
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 第几秒
    /// </summary>
    public readonly TimelineNodeWarp[] Node;


    public const int __ID__ = -2012006303;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Duration:" + Duration + ","
        + "Node:" + Luban.StringUtil.CollectionToString(Node) + ","
        + "}";
    }
}
}

