
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace MyGame
{

public sealed partial class TransferBuffWarp : Luban.BeanBase
{
    public TransferBuffWarp(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        BuffKey = (string)_obj.GetValue("BuffKey");
        Probability = (float)_obj.GetValue("Probability");
        Count = (int)_obj.GetValue("Count");
    }

    public static TransferBuffWarp DeserializeTransferBuffWarp(JToken _buf)
    {
        return new TransferBuffWarp(_buf);
    }

    public readonly string BuffKey;
    public readonly float Probability;
    public readonly int Count;


    public const int __ID__ = -245155162;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BuffKey:" + BuffKey + ","
        + "Probability:" + Probability + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

